// Agency hooks
export {
  useAgencies,
  useAgency,
  useAgencyTenants,
  useAgencyMembers,
  useAgencyStats,
  agencyKeys,
  type Agency,
  type AgencyDetails,
  type AgencyTenant,
  type AgencyMember,
  type AgencyStats,
} from "./use-agencies";

// Tenant hooks
export {
  useTenants,
  useTenant,
  useTenantMembers,
  useUpdateTenant,
  useInviteTenantMember,
  useUpdateTenantMember,
  useRemoveTenantMember,
  tenantKeys,
  type Tenant,
  type TenantDetails,
  type TenantMember,
} from "./use-tenants";

// Program hooks
export {
  usePrograms,
  useProgram,
  useProgramEnrollments,
  useProgramMentors,
  useProgramLearners,
  useCreateProgram,
  useUpdateProgram,
  useDeleteProgram,
  useEnrollUser,
  useCompleteLesson,
  programKeys,
  type Program,
  type ProgramDetails,
  type Module,
  type Lesson,
  type Enrollment,
  type EnrollUserData,
  type MentorOption,
  type LearnerOption,
  type LessonProgress,
} from "./use-programs";

// Goal hooks
export {
  useGoals,
  useGoal,
  useGoalStats,
  useCreateGoal,
  useUpdateGoal,
  useDeleteGoal,
  useAddMilestone,
  useCompleteMilestone,
  useAddGoalUpdate,
  goalKeys,
  type Goal,
  type GoalDetails,
  type GoalMilestone,
  type GoalUpdate,
  type GoalStats,
} from "./use-goals";

// Coaching hooks
export {
  useCoachingRelationships,
  useCoachingRelationship,
  useCoachingSessions,
  useCoachingSession,
  useSessionPrep,
  useSessionNotes,
  useActionItems,
  useCoachingStats,
  useCreateRelationship,
  useUpdateRelationship,
  useDeleteRelationship,
  useCreateSession,
  useUpdateSession,
  useCancelSession,
  useUpdateSessionPrep,
  useAddSessionNote,
  useCreateActionItem,
  useUpdateActionItem,
  useDeleteActionItem,
  coachingKeys,
  type CoachingRelationship,
  type CoachingSession,
  type SessionDetails,
  type SessionPrep,
  type SessionNote,
  type ActionItem,
  type CoachingStats,
  type CreateRelationshipData,
  type CreateSessionData,
  type UpdatePrepData,
  type CreateActionItemData,
} from "./use-coaching";

// Template hooks (Agency-level)
export {
  useTemplates,
  useTemplate,
  useTemplateStats,
  useCreateTemplate,
  useUpdateTemplate,
  useDeleteTemplate,
  useDuplicateTemplate,
  templateKeys,
  type AssessmentTemplate as AgencyTemplate,
  type AssessmentTemplateDetails as AgencyTemplateDetails,
  type TemplateCompetency,
  type TemplateQuestion,
  type GoalSuggestionRule,
  type TemplateStats,
  type CreateTemplateData,
  type UpdateTemplateData,
  type TemplateQueryParams,
} from "./use-templates";

// Assessment hooks
export {
  useAssessments,
  useAssessment,
  useAssessmentResults,
  useAssessmentSuggestions,
  useAssessmentInvitations,
  useMyAssessments,
  usePendingAssessments,
  useAssessmentStats,
  usePublicAssessmentForm,
  useCreateAssessment,
  useUpdateAssessment,
  useLaunchAssessment,
  useCloseAssessment,
  useReleaseResults,
  useAddInvitations,
  useRemoveInvitation,
  useSendReminder,
  useAcceptSuggestion,
  useDismissSuggestion,
  useDeleteAssessment,
  useSubmitResponses,
  useDeclineInvitation,
  assessmentKeys,
  type Assessment,
  type AssessmentDetails,
  type AssessmentTemplate,
  type AssessmentCompetency,
  type AssessmentQuestion,
  type AssessmentInvitation,
  type AssessmentResult,
  type GoalSuggestion,
  type AssessmentStats,
  type PendingAssessment,
  type RaterAssessmentForm,
  type CreateAssessmentData,
  type UpdateAssessmentData,
  type AddInvitationsData,
  type SubmitResponsesData,
} from "./use-assessments";

// Common types
export type { PaginatedResponse } from "./use-tenants";
