import type {
  OnboardingStep,
  OnboardingProgress,
  UserProfile,
  OnboardingGoal,
} from "./types";

export const defaultOnboardingSteps: OnboardingStep[] = [
  {
    id: "welcome",
    type: "welcome",
    title: "Welcome to Transformation OS",
    description: "Let's get you started with a quick overview of what you can accomplish",
    icon: "Sparkles",
    status: "pending",
    isRequired: true,
    estimatedMinutes: 1,
    actionLabel: "Let's Go",
  },
  {
    id: "profile",
    type: "profile",
    title: "Complete Your Profile",
    description: "Add your details so your team can find and connect with you",
    icon: "User",
    status: "pending",
    isRequired: true,
    estimatedMinutes: 2,
    actionLabel: "Continue",
    skipLabel: "Skip for Now",
  },
  {
    id: "goals",
    type: "goals",
    title: "Set Your First Goals",
    description: "Choose areas you'd like to focus on for your development",
    icon: "Target",
    status: "pending",
    isRequired: false,
    estimatedMinutes: 3,
    actionLabel: "Continue",
    skipLabel: "Skip for Now",
  },
  {
    id: "team",
    type: "team",
    title: "Connect with Your Team",
    description: "Invite colleagues or find your manager and direct reports",
    icon: "Users",
    status: "pending",
    isRequired: false,
    estimatedMinutes: 2,
    actionLabel: "Continue",
    skipLabel: "Skip for Now",
  },
  {
    id: "programs",
    type: "programs",
    title: "Explore Programs",
    description: "Discover learning programs tailored to your role and goals",
    icon: "BookOpen",
    status: "pending",
    isRequired: false,
    estimatedMinutes: 2,
    actionLabel: "Continue",
    skipLabel: "Skip for Now",
  },
  {
    id: "tour",
    type: "tour",
    title: "Quick Platform Tour",
    description: "A brief walkthrough of key features and navigation",
    icon: "Compass",
    status: "pending",
    isRequired: false,
    estimatedMinutes: 3,
    actionLabel: "Start Tour",
    skipLabel: "Skip Tour",
  },
  {
    id: "complete",
    type: "complete",
    title: "You're All Set!",
    description: "You're ready to start your transformation journey",
    icon: "CheckCircle",
    status: "pending",
    isRequired: true,
    estimatedMinutes: 1,
    actionLabel: "Go to Dashboard",
  },
];

export const defaultOnboardingProgress: OnboardingProgress = {
  userId: "user-1",
  currentStepIndex: 0,
  completedSteps: [],
  skippedSteps: [],
  startedAt: new Date().toISOString(),
  percentComplete: 0,
};

export const defaultUserProfile: Partial<UserProfile> = {
  firstName: "",
  lastName: "",
  email: "",
  jobTitle: "",
  department: "",
  timezone: "America/New_York",
  language: "en",
};

export const suggestedGoals: OnboardingGoal[] = [
  {
    id: "g1",
    title: "Develop Leadership Skills",
    description: "Build capabilities to lead and inspire teams effectively",
    selected: false,
  },
  {
    id: "g2",
    title: "Improve Communication",
    description: "Enhance written and verbal communication with stakeholders",
    selected: false,
  },
  {
    id: "g3",
    title: "Strategic Thinking",
    description: "Develop skills in long-term planning and decision making",
    selected: false,
  },
  {
    id: "g4",
    title: "Team Collaboration",
    description: "Build stronger working relationships and team dynamics",
    selected: false,
  },
  {
    id: "g5",
    title: "Personal Productivity",
    description: "Optimize time management and work efficiency",
    selected: false,
  },
  {
    id: "g6",
    title: "Executive Presence",
    description: "Cultivate confidence and influence in leadership settings",
    selected: false,
  },
  {
    id: "g7",
    title: "Change Management",
    description: "Learn to lead and navigate organizational change",
    selected: false,
  },
  {
    id: "g8",
    title: "Coaching Skills",
    description: "Develop ability to mentor and develop others",
    selected: false,
  },
];

export const departments = [
  "Engineering",
  "Product",
  "Design",
  "Marketing",
  "Sales",
  "Finance",
  "Human Resources",
  "Operations",
  "Customer Success",
  "Legal",
  "Executive",
  "Other",
];

export const timezones = [
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "America/Anchorage", label: "Alaska Time (AKT)" },
  { value: "Pacific/Honolulu", label: "Hawaii Time (HT)" },
  { value: "Europe/London", label: "London (GMT)" },
  { value: "Europe/Paris", label: "Paris (CET)" },
  { value: "Europe/Berlin", label: "Berlin (CET)" },
  { value: "Asia/Tokyo", label: "Tokyo (JST)" },
  { value: "Asia/Shanghai", label: "Shanghai (CST)" },
  { value: "Asia/Singapore", label: "Singapore (SGT)" },
  { value: "Australia/Sydney", label: "Sydney (AEDT)" },
];

export const stepIconConfig: Record<string, { bg: string; text: string }> = {
  welcome: { bg: "bg-purple-100", text: "text-purple-600" },
  profile: { bg: "bg-blue-100", text: "text-blue-600" },
  goals: { bg: "bg-green-100", text: "text-green-600" },
  team: { bg: "bg-orange-100", text: "text-orange-600" },
  programs: { bg: "bg-indigo-100", text: "text-indigo-600" },
  coaching: { bg: "bg-pink-100", text: "text-pink-600" },
  assessments: { bg: "bg-teal-100", text: "text-teal-600" },
  settings: { bg: "bg-gray-100", text: "text-gray-600" },
  tour: { bg: "bg-cyan-100", text: "text-cyan-600" },
  complete: { bg: "bg-accent/10", text: "text-accent" },
};
