import type { Person, Department, Team, PeopleStats } from "./types";

export const defaultDepartments: Department[] = [
  {
    id: "dept1",
    name: "Executive",
    description: "Executive leadership team",
    memberCount: 3,
  },
  {
    id: "dept2",
    name: "Engineering",
    description: "Product development and engineering",
    headId: "p3",
    memberCount: 12,
  },
  {
    id: "dept3",
    name: "Sales",
    description: "Sales and business development",
    headId: "p4",
    memberCount: 8,
  },
  {
    id: "dept4",
    name: "Marketing",
    description: "Marketing and communications",
    headId: "p5",
    memberCount: 6,
  },
  {
    id: "dept5",
    name: "Human Resources",
    description: "People operations and HR",
    headId: "p6",
    memberCount: 4,
  },
  {
    id: "dept6",
    name: "Finance",
    description: "Finance and accounting",
    headId: "p7",
    memberCount: 5,
  },
];

export const defaultTeams: Team[] = [
  {
    id: "team1",
    name: "Platform Team",
    departmentId: "dept2",
    leadId: "p8",
    memberIds: ["p8", "p9", "p10", "p11"],
  },
  {
    id: "team2",
    name: "Mobile Team",
    departmentId: "dept2",
    leadId: "p12",
    memberIds: ["p12", "p13", "p14"],
  },
  {
    id: "team3",
    name: "Enterprise Sales",
    departmentId: "dept3",
    leadId: "p15",
    memberIds: ["p15", "p16", "p17"],
  },
  {
    id: "team4",
    name: "Growth Marketing",
    departmentId: "dept4",
    leadId: "p18",
    memberIds: ["p18", "p19"],
  },
];

export const defaultPeople: Person[] = [
  // Executive
  {
    id: "p1",
    name: "James Wilson",
    email: "james.wilson@company.com",
    role: "CEO",
    title: "Chief Executive Officer",
    department: "Executive",
    departmentId: "dept1",
    employmentStatus: "active",
    userRole: "admin",
    startDate: "2018-03-15",
    location: "San Francisco, CA",
    phone: "+1 (555) 100-0001",
    directReports: 5,
    skills: ["Leadership", "Strategy", "Business Development"],
    bio: "Visionary leader with 20+ years of experience in technology and business transformation.",
  },
  {
    id: "p2",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    role: "COO",
    title: "Chief Operating Officer",
    department: "Executive",
    departmentId: "dept1",
    managerId: "p1",
    managerName: "James Wilson",
    employmentStatus: "active",
    userRole: "admin",
    startDate: "2019-06-01",
    location: "San Francisco, CA",
    phone: "+1 (555) 100-0002",
    directReports: 4,
    skills: ["Operations", "Process Optimization", "Team Building"],
    bio: "Operations expert focused on scaling businesses efficiently.",
  },
  // Engineering
  {
    id: "p3",
    name: "Michael Rodriguez",
    email: "michael.rodriguez@company.com",
    role: "VP Engineering",
    title: "Vice President of Engineering",
    department: "Engineering",
    departmentId: "dept2",
    managerId: "p1",
    managerName: "James Wilson",
    employmentStatus: "active",
    userRole: "admin",
    startDate: "2019-01-15",
    location: "San Francisco, CA",
    phone: "+1 (555) 100-0003",
    directReports: 4,
    skills: ["Software Architecture", "Team Leadership", "Agile"],
    bio: "Engineering leader passionate about building scalable systems and high-performing teams.",
  },
  // Sales
  {
    id: "p4",
    name: "Emily Thompson",
    email: "emily.thompson@company.com",
    role: "VP Sales",
    title: "Vice President of Sales",
    department: "Sales",
    departmentId: "dept3",
    managerId: "p2",
    managerName: "Sarah Chen",
    employmentStatus: "active",
    userRole: "manager",
    startDate: "2020-02-01",
    location: "New York, NY",
    phone: "+1 (555) 100-0004",
    directReports: 3,
    skills: ["Sales Strategy", "Enterprise Sales", "Negotiation"],
  },
  // Marketing
  {
    id: "p5",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "VP Marketing",
    title: "Vice President of Marketing",
    department: "Marketing",
    departmentId: "dept4",
    managerId: "p2",
    managerName: "Sarah Chen",
    employmentStatus: "active",
    userRole: "manager",
    startDate: "2020-05-15",
    location: "San Francisco, CA",
    phone: "+1 (555) 100-0005",
    directReports: 2,
    skills: ["Brand Strategy", "Digital Marketing", "Content"],
  },
  // HR
  {
    id: "p6",
    name: "Amanda Foster",
    email: "amanda.foster@company.com",
    role: "HR Director",
    title: "Director of Human Resources",
    department: "Human Resources",
    departmentId: "dept5",
    managerId: "p2",
    managerName: "Sarah Chen",
    employmentStatus: "active",
    userRole: "manager",
    startDate: "2019-09-01",
    location: "San Francisco, CA",
    phone: "+1 (555) 100-0006",
    directReports: 3,
    skills: ["Talent Acquisition", "Employee Relations", "HR Strategy"],
  },
  // Finance
  {
    id: "p7",
    name: "Robert Martinez",
    email: "robert.martinez@company.com",
    role: "CFO",
    title: "Chief Financial Officer",
    department: "Finance",
    departmentId: "dept6",
    managerId: "p1",
    managerName: "James Wilson",
    employmentStatus: "active",
    userRole: "admin",
    startDate: "2019-04-01",
    location: "San Francisco, CA",
    phone: "+1 (555) 100-0007",
    directReports: 2,
    skills: ["Financial Planning", "M&A", "Investor Relations"],
  },
  // Engineering Team Members
  {
    id: "p8",
    name: "Jennifer Lee",
    email: "jennifer.lee@company.com",
    role: "Engineering Manager",
    title: "Engineering Manager - Platform",
    department: "Engineering",
    departmentId: "dept2",
    team: "Platform Team",
    teamId: "team1",
    managerId: "p3",
    managerName: "Michael Rodriguez",
    employmentStatus: "active",
    userRole: "manager",
    startDate: "2020-03-15",
    location: "San Francisco, CA",
    directReports: 4,
    skills: ["Backend Development", "System Design", "Python", "Go"],
  },
  {
    id: "p9",
    name: "Alex Johnson",
    email: "alex.johnson@company.com",
    role: "Senior Engineer",
    title: "Senior Software Engineer",
    department: "Engineering",
    departmentId: "dept2",
    team: "Platform Team",
    teamId: "team1",
    managerId: "p8",
    managerName: "Jennifer Lee",
    employmentStatus: "active",
    userRole: "employee",
    startDate: "2021-01-10",
    location: "Austin, TX",
    skills: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "p10",
    name: "Maria Garcia",
    email: "maria.garcia@company.com",
    role: "Software Engineer",
    title: "Software Engineer II",
    department: "Engineering",
    departmentId: "dept2",
    team: "Platform Team",
    teamId: "team1",
    managerId: "p8",
    managerName: "Jennifer Lee",
    employmentStatus: "active",
    userRole: "employee",
    startDate: "2022-06-01",
    location: "Remote",
    skills: ["Python", "AWS", "Kubernetes"],
  },
  {
    id: "p11",
    name: "Chris Taylor",
    email: "chris.taylor@company.com",
    role: "Junior Engineer",
    title: "Software Engineer I",
    department: "Engineering",
    departmentId: "dept2",
    team: "Platform Team",
    teamId: "team1",
    managerId: "p8",
    managerName: "Jennifer Lee",
    employmentStatus: "active",
    userRole: "employee",
    startDate: "2024-01-15",
    location: "San Francisco, CA",
    skills: ["JavaScript", "React", "SQL"],
  },
  {
    id: "p12",
    name: "Kevin Patel",
    email: "kevin.patel@company.com",
    role: "Engineering Manager",
    title: "Engineering Manager - Mobile",
    department: "Engineering",
    departmentId: "dept2",
    team: "Mobile Team",
    teamId: "team2",
    managerId: "p3",
    managerName: "Michael Rodriguez",
    employmentStatus: "active",
    userRole: "manager",
    startDate: "2020-08-01",
    location: "San Francisco, CA",
    directReports: 3,
    skills: ["iOS", "Android", "React Native", "Flutter"],
  },
  {
    id: "p13",
    name: "Lisa Wang",
    email: "lisa.wang@company.com",
    role: "iOS Developer",
    title: "Senior iOS Developer",
    department: "Engineering",
    departmentId: "dept2",
    team: "Mobile Team",
    teamId: "team2",
    managerId: "p12",
    managerName: "Kevin Patel",
    employmentStatus: "active",
    userRole: "employee",
    startDate: "2021-04-01",
    location: "Seattle, WA",
    skills: ["Swift", "iOS", "UIKit", "SwiftUI"],
  },
  {
    id: "p14",
    name: "Tom Anderson",
    email: "tom.anderson@company.com",
    role: "Android Developer",
    title: "Android Developer",
    department: "Engineering",
    departmentId: "dept2",
    team: "Mobile Team",
    teamId: "team2",
    managerId: "p12",
    managerName: "Kevin Patel",
    employmentStatus: "on_leave",
    userRole: "employee",
    startDate: "2022-02-15",
    location: "Remote",
    skills: ["Kotlin", "Android", "Jetpack Compose"],
  },
  // Sales Team
  {
    id: "p15",
    name: "Rachel Green",
    email: "rachel.green@company.com",
    role: "Sales Manager",
    title: "Enterprise Sales Manager",
    department: "Sales",
    departmentId: "dept3",
    team: "Enterprise Sales",
    teamId: "team3",
    managerId: "p4",
    managerName: "Emily Thompson",
    employmentStatus: "active",
    userRole: "manager",
    startDate: "2021-03-01",
    location: "New York, NY",
    directReports: 2,
    skills: ["Enterprise Sales", "Account Management", "CRM"],
  },
  {
    id: "p16",
    name: "Mark Stevens",
    email: "mark.stevens@company.com",
    role: "Account Executive",
    title: "Senior Account Executive",
    department: "Sales",
    departmentId: "dept3",
    team: "Enterprise Sales",
    teamId: "team3",
    managerId: "p15",
    managerName: "Rachel Green",
    employmentStatus: "active",
    userRole: "employee",
    startDate: "2021-09-01",
    location: "Chicago, IL",
    skills: ["B2B Sales", "Negotiation", "Salesforce"],
  },
  {
    id: "p17",
    name: "Nicole Brown",
    email: "nicole.brown@company.com",
    role: "SDR",
    title: "Sales Development Representative",
    department: "Sales",
    departmentId: "dept3",
    team: "Enterprise Sales",
    teamId: "team3",
    managerId: "p15",
    managerName: "Rachel Green",
    employmentStatus: "active",
    userRole: "employee",
    startDate: "2023-06-01",
    location: "New York, NY",
    skills: ["Lead Generation", "Cold Calling", "Email Outreach"],
  },
  // Marketing Team
  {
    id: "p18",
    name: "Sophie Turner",
    email: "sophie.turner@company.com",
    role: "Marketing Manager",
    title: "Growth Marketing Manager",
    department: "Marketing",
    departmentId: "dept4",
    team: "Growth Marketing",
    teamId: "team4",
    managerId: "p5",
    managerName: "David Kim",
    employmentStatus: "active",
    userRole: "manager",
    startDate: "2021-07-01",
    location: "San Francisco, CA",
    directReports: 1,
    skills: ["Growth Hacking", "Analytics", "SEO/SEM"],
  },
  {
    id: "p19",
    name: "Daniel Park",
    email: "daniel.park@company.com",
    role: "Content Specialist",
    title: "Content Marketing Specialist",
    department: "Marketing",
    departmentId: "dept4",
    team: "Growth Marketing",
    teamId: "team4",
    managerId: "p18",
    managerName: "Sophie Turner",
    employmentStatus: "active",
    userRole: "employee",
    startDate: "2022-11-01",
    location: "Remote",
    skills: ["Content Writing", "SEO", "Social Media"],
  },
  // Contractor
  {
    id: "p20",
    name: "Sam Mitchell",
    email: "sam.mitchell@contractor.com",
    role: "Contractor",
    title: "UX Design Contractor",
    department: "Engineering",
    departmentId: "dept2",
    managerId: "p3",
    managerName: "Michael Rodriguez",
    employmentStatus: "contractor",
    userRole: "contractor",
    startDate: "2024-09-01",
    location: "Remote",
    skills: ["UX Design", "Figma", "User Research"],
  },
];

export const defaultPeopleStats: PeopleStats = {
  totalPeople: 20,
  activeEmployees: 18,
  onLeave: 1,
  contractors: 1,
  newThisMonth: 2,
  departments: 6,
  teams: 4,
};

export const employmentStatusConfig: Record<
  string,
  { label: string; bg: string; text: string }
> = {
  active: { label: "Active", bg: "bg-green-100", text: "text-green-700" },
  on_leave: { label: "On Leave", bg: "bg-yellow-100", text: "text-yellow-700" },
  terminated: { label: "Terminated", bg: "bg-red-100", text: "text-red-700" },
  contractor: { label: "Contractor", bg: "bg-purple-100", text: "text-purple-700" },
};

export const userRoleConfig: Record<
  string,
  { label: string; bg: string; text: string }
> = {
  admin: { label: "Admin", bg: "bg-red-100", text: "text-red-700" },
  manager: { label: "Manager", bg: "bg-blue-100", text: "text-blue-700" },
  employee: { label: "Employee", bg: "bg-gray-100", text: "text-gray-700" },
  contractor: { label: "Contractor", bg: "bg-purple-100", text: "text-purple-700" },
};
