import type {
  Client,
  AgencyTemplate,
  BrandingConfig,
  AgencyStats,
  AgencyBilling,
} from "./types";

export const defaultAgencyStats: AgencyStats = {
  totalClients: 24,
  activeClients: 21,
  totalUsers: 1842,
  totalMRR: 48500,
  mrrGrowth: 12.5,
  avgUsersPerClient: 77,
  trialConversionRate: 68,
  churnRate: 2.1,
};

export const defaultClients: Client[] = [
  {
    id: "c1",
    name: "Acme Corporation",
    domain: "acme.com",
    industry: "Technology",
    status: "active",
    subscriptionTier: "enterprise",
    createdAt: "2024-03-15",
    users: 156,
    usersLimit: 200,
    activePrograms: 8,
    contactName: "Sarah Chen",
    contactEmail: "sarah.chen@acme.com",
    mrr: 4999,
    lastActivity: "2025-01-30T14:30:00Z",
  },
  {
    id: "c2",
    name: "Global Finance Inc",
    domain: "globalfinance.com",
    industry: "Finance",
    status: "active",
    subscriptionTier: "enterprise",
    createdAt: "2024-01-10",
    users: 312,
    usersLimit: 500,
    activePrograms: 12,
    contactName: "Michael Roberts",
    contactEmail: "m.roberts@globalfinance.com",
    mrr: 7999,
    lastActivity: "2025-01-30T09:15:00Z",
  },
  {
    id: "c3",
    name: "HealthFirst Medical",
    domain: "healthfirst.org",
    industry: "Healthcare",
    status: "active",
    subscriptionTier: "professional",
    createdAt: "2024-06-20",
    users: 89,
    usersLimit: 100,
    activePrograms: 5,
    contactName: "Dr. Emily Watson",
    contactEmail: "e.watson@healthfirst.org",
    mrr: 1999,
    lastActivity: "2025-01-29T16:45:00Z",
  },
  {
    id: "c4",
    name: "TechStart Solutions",
    domain: "techstart.io",
    industry: "Technology",
    status: "trial",
    subscriptionTier: "professional",
    createdAt: "2025-01-15",
    users: 24,
    usersLimit: 50,
    activePrograms: 2,
    contactName: "Alex Kim",
    contactEmail: "alex@techstart.io",
    mrr: 0,
    lastActivity: "2025-01-30T11:00:00Z",
  },
  {
    id: "c5",
    name: "Retail Giants Co",
    domain: "retailgiants.com",
    industry: "Retail",
    status: "active",
    subscriptionTier: "professional",
    createdAt: "2024-08-05",
    users: 145,
    usersLimit: 200,
    activePrograms: 6,
    contactName: "Jennifer Lee",
    contactEmail: "jlee@retailgiants.com",
    mrr: 2499,
    lastActivity: "2025-01-28T10:30:00Z",
  },
  {
    id: "c6",
    name: "EduLearn Academy",
    domain: "edulearn.edu",
    industry: "Education",
    status: "active",
    subscriptionTier: "starter",
    createdAt: "2024-09-12",
    users: 45,
    usersLimit: 50,
    activePrograms: 3,
    contactName: "Prof. David Miller",
    contactEmail: "dmiller@edulearn.edu",
    mrr: 499,
    lastActivity: "2025-01-27T14:20:00Z",
  },
  {
    id: "c7",
    name: "Manufacturing Plus",
    domain: "mfgplus.com",
    industry: "Manufacturing",
    status: "suspended",
    subscriptionTier: "professional",
    createdAt: "2024-04-22",
    users: 78,
    usersLimit: 100,
    activePrograms: 0,
    contactName: "Robert Taylor",
    contactEmail: "rtaylor@mfgplus.com",
    mrr: 0,
    lastActivity: "2024-12-15T09:00:00Z",
  },
  {
    id: "c8",
    name: "Creative Agency Ltd",
    domain: "creativeagency.co",
    industry: "Marketing",
    status: "active",
    subscriptionTier: "starter",
    createdAt: "2024-11-01",
    users: 28,
    usersLimit: 50,
    activePrograms: 2,
    contactName: "Lisa Park",
    contactEmail: "lisa@creativeagency.co",
    mrr: 499,
    lastActivity: "2025-01-30T08:45:00Z",
  },
];

export const defaultTemplates: AgencyTemplate[] = [
  {
    id: "t1",
    name: "Leadership 360 Assessment",
    description: "Comprehensive leadership assessment with self, manager, peer, and direct report feedback",
    type: "assessment",
    category: "Leadership",
    isPublished: true,
    usageCount: 156,
    createdAt: "2024-02-10",
    updatedAt: "2024-11-15",
    createdBy: "Admin",
  },
  {
    id: "t2",
    name: "New Manager Bootcamp",
    description: "12-week program for first-time managers covering essential leadership skills",
    type: "program",
    category: "Leadership",
    isPublished: true,
    usageCount: 89,
    createdAt: "2024-01-15",
    updatedAt: "2024-12-01",
    createdBy: "Admin",
  },
  {
    id: "t3",
    name: "Executive Presence Program",
    description: "Advanced program for senior leaders focusing on strategic communication",
    type: "program",
    category: "Executive",
    isPublished: true,
    usageCount: 45,
    createdAt: "2024-03-20",
    updatedAt: "2024-10-30",
    createdBy: "Admin",
  },
  {
    id: "t4",
    name: "Team Effectiveness Assessment",
    description: "Evaluate team dynamics, collaboration, and performance",
    type: "assessment",
    category: "Teams",
    isPublished: true,
    usageCount: 78,
    createdAt: "2024-04-05",
    updatedAt: "2024-09-20",
    createdBy: "Admin",
  },
  {
    id: "t5",
    name: "SMART Goals Framework",
    description: "Template for setting and tracking SMART goals",
    type: "goal",
    category: "Performance",
    isPublished: true,
    usageCount: 234,
    createdAt: "2024-01-01",
    updatedAt: "2024-08-15",
    createdBy: "Admin",
  },
  {
    id: "t6",
    name: "Change Management Program",
    description: "Guide teams through organizational change with structured learning",
    type: "program",
    category: "Change",
    isPublished: false,
    usageCount: 0,
    createdAt: "2025-01-10",
    updatedAt: "2025-01-25",
    createdBy: "Admin",
  },
  {
    id: "t7",
    name: "Manager Effectiveness Survey",
    description: "Quick assessment for evaluating manager performance",
    type: "assessment",
    category: "Leadership",
    isPublished: true,
    usageCount: 112,
    createdAt: "2024-05-15",
    updatedAt: "2024-11-10",
    createdBy: "Admin",
  },
  {
    id: "t8",
    name: "OKR Template",
    description: "Objectives and Key Results framework for goal setting",
    type: "goal",
    category: "Performance",
    isPublished: true,
    usageCount: 189,
    createdAt: "2024-02-28",
    updatedAt: "2024-07-20",
    createdBy: "Admin",
  },
];

export const defaultBranding: BrandingConfig = {
  primaryColor: "#1F2937",
  accentColor: "#E53E3E",
  companyName: "Results Tracking System",
  supportEmail: "support@transformationos.com",
  customDomain: "app.transformationos.com",
};

export const defaultAgencyBilling: AgencyBilling = {
  totalMRR: 48500,
  totalARR: 582000,
  outstandingInvoices: 3250,
  revenueByTier: {
    starter: 4990,
    professional: 22485,
    enterprise: 20997,
  },
  recentTransactions: [
    {
      id: "tr1",
      clientId: "c2",
      clientName: "Global Finance Inc",
      amount: 7999,
      type: "subscription",
      status: "completed",
      date: "2025-01-01",
    },
    {
      id: "tr2",
      clientId: "c1",
      clientName: "Acme Corporation",
      amount: 4999,
      type: "subscription",
      status: "completed",
      date: "2025-01-01",
    },
    {
      id: "tr3",
      clientId: "c3",
      clientName: "HealthFirst Medical",
      amount: 1999,
      type: "subscription",
      status: "completed",
      date: "2025-01-01",
    },
    {
      id: "tr4",
      clientId: "c5",
      clientName: "Retail Giants Co",
      amount: 500,
      type: "addon",
      status: "completed",
      date: "2025-01-15",
    },
    {
      id: "tr5",
      clientId: "c7",
      clientName: "Manufacturing Plus",
      amount: -1999,
      type: "refund",
      status: "completed",
      date: "2024-12-20",
    },
  ],
};

export const clientStatusConfig: Record<
  string,
  { label: string; bg: string; text: string }
> = {
  active: { label: "Active", bg: "bg-green-100", text: "text-green-700" },
  trial: { label: "Trial", bg: "bg-blue-100", text: "text-blue-700" },
  suspended: { label: "Suspended", bg: "bg-yellow-100", text: "text-yellow-700" },
  churned: { label: "Churned", bg: "bg-red-100", text: "text-red-700" },
};

export const tierConfig: Record<
  string,
  { label: string; bg: string; text: string }
> = {
  starter: { label: "Starter", bg: "bg-gray-100", text: "text-gray-700" },
  professional: { label: "Professional", bg: "bg-purple-100", text: "text-purple-700" },
  enterprise: { label: "Enterprise", bg: "bg-accent/10", text: "text-accent" },
};

export const templateTypeConfig: Record<
  string,
  { label: string; bg: string; text: string }
> = {
  program: { label: "Program", bg: "bg-blue-100", text: "text-blue-700" },
  assessment: { label: "Assessment", bg: "bg-purple-100", text: "text-purple-700" },
  goal: { label: "Goal", bg: "bg-green-100", text: "text-green-700" },
};
